sudo: required

services:
  - docker

before_install:
  - docker build -t oliverloenning/si-test-frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run oliverloenning/si-test-frontend npm run test:unit
