version: "3"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "1234:8080"
  mom:
    image: rmohr/activemq
  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "test"
